import './index.scss'
import './blocks/header/top-nav/top-nav.js'
import './blocks/main/gallery/images-list/images-list.js'
import './blocks/main/key-properties/key-properties.js'
import './blocks/footer/footer.js'
import './php/php.js'